"""
Django settings for iPLMver2 project.

Generated by 'django-admin startproject' using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
SIMPLEUI_HOME_INFO = False
SIMPLEUI_INDEX = 'http://127.0.0.1:8000/admin/'
SIMPLEUI_LOGO = 'http://127.0.0.1:8000/static/CRS/images/landingPage/iplm01.png'
SIMPLEUI_ANALYSIS = False
SIMPLEUI_DEFAULT_THEME = 'e-blue.css'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'sz68q!bdy_(f^!q%azzlt-s)r0_qb7e@jbh)7=68u!z*(i5+^n'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*','iplm-site.herokuapp.com','.herokuapp.com']


# Application definition

INSTALLED_APPS = [
    'simpleui',
    'admin_confirm',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'CRS.apps.CrsConfig',
    'django_admin_listfilter_dropdown',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #Session-timeout
    'django_session_timeout.middleware.SessionTimeoutMiddleware',
    #auto-logout
    'django_auto_logout.middleware.auto_logout'
]

ROOT_URLCONF = 'iPLMver2.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'template')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                #auto-logout
                'django_auto_logout.context_processors.auto_logout_client'
            ],
        },
    },
]

WSGI_APPLICATION = 'iPLMver2.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
'default': {
'ENGINE': 'django.db.backends.mysql',
'NAME': 'iplmdatabase',
'USER': 'root',
'PASSWORD': '',
'HOST': '',
'PORT': '',
'OPTIONS': {
'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"
}
}
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
    'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
    'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
    'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {'NAME': 'CRS.validators.UppercaseValidator', },
    {'NAME': 'CRS.validators.LowercaseValidator', },
    {'NAME': 'CRS.validators.SymbolValidator', },
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', },
]



# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_L10N = False

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

STATICFILES_DIR = [
    os.path.join(BASE_DIR, 'static')
]

MEDIA_ROOT = os.path.join(BASE_DIR, 'files')

MEDIA_URL = '/files/'
AUTH_USER_MODEL = 'CRS.User'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'iplm.haribon@gmail.com'
EMAIL_HOST_PASSWORD = 'zcsedqhoedkiwtic'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

LOGOUT_REDIRECT_URL = 'index'

SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_SAVE_EVERY_REQUEST = True

AUTO_LOGOUT = {
    'IDLE_TIME': timedelta(minutes=60), #sinet ko lang to test
    'MESSAGE': 'The session has expired. Please login again to continue.',
    'REDIRECT_TO_LOGIN_IMMEDIATELY': True,
}

SIMPLEUI_ICON = {
    'CRS': 'fas fa-window-restore',
    'Academic Year Information': 'fas fa-calendar',
    'Block Sections': 'fas fa-school',
    'CRS Checklist': 'fas fa-clipboard-list',
    'CRS Grades': 'fas fa-clipboard',
    'Chairperson Information': 'fas fa-user-check',
    'Checklists': 'fas fa-clipboard-check',
    'Colleges': 'fas fa-university',
    'Course List': 'fas fa-list',
    'Curricula': 'fas fa-calendar-day',
    'Curriculum Information': 'fas fa-info',
    'Departments': 'fas fa-building',
    'Events': 'fas fa-calendar-day',
    'Faculty Applicants': 'fas fa-chalkboard-teacher',
    'Faculty Information': 'fas fa-sitemap',
    'HD Applicants': 'fas fa-user-plus',
    'HD Clearance Forms': 'fas fa-file-alt',
    'HD Dropping Forms': 'fas fa-archive',
    'HD Transfer Certificates': 'fas fa-certificate',
    'LOA Applicants': 'fas fa-user-minus',
    'LOA Clearance Forms': 'fas fa-file',
    'LOA Forms': 'fas fa-folder-open',
    'Notifications': 'fas fa-bell',
    'OJT Applicants': 'fas fa-portrait',
    'Outbound Shifter Applicants': 'fas fa-random',
    'Room Information': 'fas fa-question',
    'Shifter Applicants': 'fas fa-user-edit',
    'Shifting Form': 'fas fa-file-export',
    'Student Information': 'fas fa-user-graduate',
    'Student Scheduling': 'fas fa-calendar-alt',
    'Study Plan Applicants': 'fas fa-user-friends',
    'Study Plans': 'fas fa-pencil-ruler',
    'Subject Information': 'fas fa-info-circle',
    'Transferee Applicants': 'fas fa-exchange-alt',
    'Users': 'fas fa-users'
}